apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment      # name of deployment
  # namespace: prod     # name of namespace

spec:
  replicas: 1       # giving instruction to create 2 replica(pods) of application
  selector:
    matchLabels:      # telling deployemtn which pods to manage
      app: todo   # it will manage only pods that have labels
  template:           #he Pods created by this Deployment will be labeled with app: nginx-lab.
    metadata:
      labels:
        app: todo
    spec:
      containers:
       - name: todocontainer
         image: n91k16/kapiltodo
         ports:
          - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: brave-deployment    # name of deployment
  # namespace: prod     # name of namespace

spec:
  replicas: 1        # giving instruction to create 2 replica(pods) of application
  selector:
    matchLabels:      # telling deployemtn which pods to manage
      app: brave-labels   # it will manage only pods that have labels
  template:           #he Pods created by this Deployment will be labeled with app: nginx-lab.
    metadata:
      labels:
        app: brave-labels
    spec:
      containers:
       - name: bravecontainer
         image: linuxserver/brave

         ports:
          - containerPort: 80

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-deployment    # name of deployment
  # namespace: prod     # name of namespace

spec:
  replicas: 1        # giving instruction to create 2 replica(pods) of application
  selector:
    matchLabels:      # telling deployemtn which pods to manage
      app: firefox-labels   # it will manage only pods that have labels
  template:           #he Pods created by this Deployment will be labeled with app: nginx-lab.
    metadata:
      labels:
        app: firefox-labels
    spec:
      containers:
       - name: firefox-containers
         image: linuxserver/firefox
         ports:
          - containerPort: 80



