apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment      # name of deployment
  # namespace: prod     # name of namespace

spec:
  replicas: 1       # giving instruction to create 2 replica(pods) of application
  selector:
    matchLabels:      # telling deployemtn which pods to manage
      app: todo   # it will manage only pods that have labels
  template:           #he Pods created by this Deployment will be labeled with app: nginx-lab.
    metadata:
      labels:
        app: todo
    spec:
      containers:
       - name: todocontainer
         image: nginx
         ports:
          - containerPort: 80

